import Foundation

/// The 26-applicant pool for the review deck (`web/v2/venue.html`
/// `APPLICANTS`, ids `a1`...`a26`) — transcribed verbatim, including Sara
/// Capriotti (`a1`) as an applicant of the venue's own "Late Lounge" (she is
/// simultaneously the demo member and one of the 26 people the venue reviews;
/// see `MemberProfile` doc comment for the reputation-score disagreement this
/// creates between her own Profile screen and this record).
extension DemoWorldSeed {
    public static func applicants() -> [ApplicantCard] {
        [
            ApplicantCard(id: "a1", name: "Sara Capriotti", gender: "female", photoName: "sara",
                qualityScore: 0.94, instagramFollowers: 28400, tiktokFollowers: 51200,
                instagramURL: "https://instagram.com/capriottisara", tiktokURL: "https://tiktok.com/@capriottisara",
                reputationScore: 9.1, nights: 18, shows: 17, noShows: 1, strikes: 0, withYou: 3,
                audienceFemalePct: 0.68, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.72),
                    AudienceCountry(label: "UAE", pct: 0.12),
                    AudienceCountry(label: "France", pct: 0.08),
                ]),
            ApplicantCard(id: "a2", name: "Karim Haddad", gender: "male", photoName: "karim",
                qualityScore: 0.88, instagramFollowers: 14200, tiktokFollowers: 9800,
                instagramURL: "https://instagram.com/karim", tiktokURL: "https://tiktok.com/@karim",
                reputationScore: 8.7, nights: 12, shows: 11, noShows: 1, strikes: 0, withYou: 2,
                audienceFemalePct: 0.42, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.70),
                    AudienceCountry(label: "UAE", pct: 0.14),
                    AudienceCountry(label: "KSA", pct: 0.06),
                ]),
            ApplicantCard(id: "a3", name: "Lea Nassar", gender: "female", photoName: "lina",
                qualityScore: 0.91, instagramFollowers: 46100, tiktokFollowers: 120300,
                instagramURL: "https://instagram.com/lea", otherURL: "https://leanassar.com",
                reputationScore: 9.4, nights: 22, shows: 22, noShows: 0, strikes: 0, withYou: 4,
                audienceFemalePct: 0.71, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.65),
                    AudienceCountry(label: "UAE", pct: 0.18),
                    AudienceCountry(label: "KSA", pct: 0.07),
                ]),
            ApplicantCard(id: "a4", name: "Tariq Bou", gender: "male", photoName: "rami",
                qualityScore: 0.79, instagramFollowers: 8200, tiktokFollowers: 21000,
                instagramURL: "https://instagram.com/tariq", tiktokURL: "https://tiktok.com/@tariq",
                reputationScore: 8.2, nights: 7, shows: 6, noShows: 1, strikes: 0, withYou: 1,
                audienceFemalePct: 0.38, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.74),
                    AudienceCountry(label: "Cyprus", pct: 0.10),
                    AudienceCountry(label: "UAE", pct: 0.08),
                ]),
            ApplicantCard(id: "a5", name: "Nour Khoury", gender: "female", photoName: "nour",
                qualityScore: 0.86, instagramFollowers: 33000, tiktokFollowers: 5400,
                instagramURL: "https://instagram.com/nour", tiktokURL: "https://tiktok.com/@nour",
                reputationScore: 8.9, nights: 14, shows: 13, noShows: 1, strikes: 0, withYou: 2,
                audienceFemalePct: 0.64, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.70),
                    AudienceCountry(label: "UAE", pct: 0.14),
                    AudienceCountry(label: "KSA", pct: 0.06),
                ]),
            ApplicantCard(id: "a6", name: "Maya Fares", gender: "female", photoName: "maya",
                qualityScore: 0.97, instagramFollowers: 88000, tiktokFollowers: 240000,
                instagramURL: "https://instagram.com/maya", tiktokURL: "https://tiktok.com/@maya",
                reputationScore: 9.6, nights: 24, shows: 24, noShows: 0, strikes: 0, withYou: 4,
                audienceFemalePct: 0.78, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.60),
                    AudienceCountry(label: "UAE", pct: 0.20),
                    AudienceCountry(label: "France", pct: 0.08),
                ]),
            ApplicantCard(id: "a7", name: "Jad Aoun", gender: "male", photoName: "karim",
                qualityScore: 0.72, instagramFollowers: 5100, tiktokFollowers: 3200,
                instagramURL: "https://instagram.com/jad",
                reputationScore: 7.9, nights: 5, shows: 4, noShows: 1, strikes: 1, withYou: 0,
                audienceFemalePct: 0.41, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.80),
                    AudienceCountry(label: "Cyprus", pct: 0.09),
                    AudienceCountry(label: "Qatar", pct: 0.05),
                ]),
            ApplicantCard(id: "a8", name: "Yara Saad", gender: "female", photoName: "yasmine",
                qualityScore: 0.83, instagramFollowers: 19500, tiktokFollowers: 42000,
                instagramURL: "https://instagram.com/yara", tiktokURL: "https://tiktok.com/@yara",
                reputationScore: 8.6, nights: 10, shows: 10, noShows: 0, strikes: 0, withYou: 2,
                audienceFemalePct: 0.66, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.68),
                    AudienceCountry(label: "UAE", pct: 0.16),
                    AudienceCountry(label: "KSA", pct: 0.08),
                ]),
            ApplicantCard(id: "a9", name: "Lea Khoury", gender: "female", photoName: "sara",
                qualityScore: 0.82, instagramFollowers: 22000, tiktokFollowers: 38000,
                instagramURL: "https://instagram.com/leakhoury", tiktokURL: "https://tiktok.com/@leakhoury",
                reputationScore: 8.8, nights: 9, shows: 9, noShows: 0, strikes: 0, withYou: 1,
                audienceFemalePct: 0.65, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.71),
                    AudienceCountry(label: "UAE", pct: 0.13),
                    AudienceCountry(label: "KSA", pct: 0.07),
                ]),
            ApplicantCard(id: "a10", name: "Maya Rahme", gender: "female", photoName: "maya",
                qualityScore: 0.87, instagramFollowers: 34000, tiktokFollowers: 61000,
                instagramURL: "https://instagram.com/mayarahme", tiktokURL: "https://tiktok.com/@mayarahme",
                reputationScore: 9.0, nights: 11, shows: 11, noShows: 0, strikes: 0, withYou: 2,
                audienceFemalePct: 0.70, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.66),
                    AudienceCountry(label: "UAE", pct: 0.17),
                    AudienceCountry(label: "France", pct: 0.09),
                ]),
            ApplicantCard(id: "a11", name: "Nour Saab", gender: "female", photoName: "nour",
                qualityScore: 0.79, instagramFollowers: 15000, tiktokFollowers: 27000,
                instagramURL: "https://instagram.com/noursaab", tiktokURL: "https://tiktok.com/@noursaab",
                reputationScore: 8.3, nights: 6, shows: 6, noShows: 0, strikes: 0, withYou: 1,
                audienceFemalePct: 0.62, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.75),
                    AudienceCountry(label: "UAE", pct: 0.12),
                    AudienceCountry(label: "Qatar", pct: 0.06),
                ]),
            ApplicantCard(id: "a12", name: "Yara Chami", gender: "female", photoName: "yasmine",
                qualityScore: 0.84, instagramFollowers: 27000, tiktokFollowers: 45000,
                instagramURL: "https://instagram.com/yarachami", tiktokURL: "https://tiktok.com/@yarachami",
                reputationScore: 8.7, nights: 13, shows: 12, noShows: 1, strikes: 0, withYou: 2,
                audienceFemalePct: 0.67, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.69),
                    AudienceCountry(label: "UAE", pct: 0.15),
                    AudienceCountry(label: "KSA", pct: 0.07),
                ]),
            ApplicantCard(id: "a13", name: "Tala Aoun", gender: "female", photoName: "tala",
                qualityScore: 0.76, instagramFollowers: 12000, tiktokFollowers: 19000,
                instagramURL: "https://instagram.com/talaaoun", tiktokURL: "https://tiktok.com/@talaaoun",
                reputationScore: 8.1, nights: 5, shows: 5, noShows: 0, strikes: 0, withYou: 0,
                audienceFemalePct: 0.63, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.76),
                    AudienceCountry(label: "Cyprus", pct: 0.10),
                    AudienceCountry(label: "UAE", pct: 0.07),
                ]),
            ApplicantCard(id: "a14", name: "Rita Sleiman", gender: "female", photoName: "sara",
                qualityScore: 0.88, instagramFollowers: 41000, tiktokFollowers: 78000,
                instagramURL: "https://instagram.com/ritasleiman", tiktokURL: "https://tiktok.com/@ritasleiman",
                reputationScore: 9.2, nights: 19, shows: 18, noShows: 1, strikes: 0, withYou: 3,
                audienceFemalePct: 0.72, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.64),
                    AudienceCountry(label: "UAE", pct: 0.18),
                    AudienceCountry(label: "France", pct: 0.10),
                ]),
            ApplicantCard(id: "a15", name: "Dana Fakhry", gender: "female", photoName: "lina",
                qualityScore: 0.81, instagramFollowers: 18000, tiktokFollowers: 30000,
                instagramURL: "https://instagram.com/danafakhry", tiktokURL: "https://tiktok.com/@danafakhry",
                reputationScore: 8.5, nights: 8, shows: 8, noShows: 0, strikes: 0, withYou: 1,
                audienceFemalePct: 0.66, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.72),
                    AudienceCountry(label: "UAE", pct: 0.14),
                    AudienceCountry(label: "Qatar", pct: 0.07),
                ]),
            ApplicantCard(id: "a16", name: "Lana Matar", gender: "female", photoName: "maya",
                qualityScore: 0.92, instagramFollowers: 55000, tiktokFollowers: 92000,
                instagramURL: "https://instagram.com/lanamatar", tiktokURL: "https://tiktok.com/@lanamatar",
                reputationScore: 9.3, nights: 20, shows: 20, noShows: 0, strikes: 0, withYou: 4,
                audienceFemalePct: 0.75, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.62),
                    AudienceCountry(label: "UAE", pct: 0.20),
                    AudienceCountry(label: "KSA", pct: 0.09),
                ]),
            ApplicantCard(id: "a17", name: "Cyrine Nassar", gender: "female", photoName: "nour",
                qualityScore: 0.78, instagramFollowers: 11000, tiktokFollowers: 16000,
                instagramURL: "https://instagram.com/cyrinenassar", tiktokURL: "https://tiktok.com/@cyrinenassar",
                reputationScore: 8.2, nights: 4, shows: 4, noShows: 0, strikes: 0, withYou: 0,
                audienceFemalePct: 0.61, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.78),
                    AudienceCountry(label: "Cyprus", pct: 0.08),
                    AudienceCountry(label: "UAE", pct: 0.07),
                ]),
            ApplicantCard(id: "a18", name: "Joelle Abou Jaoude", gender: "female", photoName: "yasmine",
                qualityScore: 0.85, instagramFollowers: 31000, tiktokFollowers: 54000,
                instagramURL: "https://instagram.com/joelleaj", tiktokURL: "https://tiktok.com/@joelleaj",
                reputationScore: 8.9, nights: 15, shows: 14, noShows: 1, strikes: 0, withYou: 2,
                audienceFemalePct: 0.68, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.68),
                    AudienceCountry(label: "UAE", pct: 0.16),
                    AudienceCountry(label: "France", pct: 0.08),
                ]),
            ApplicantCard(id: "a19", name: "Karen Daou", gender: "female", photoName: "tala",
                qualityScore: 0.71, instagramFollowers: 9000, tiktokFollowers: 12000,
                instagramURL: "https://instagram.com/karendaou", tiktokURL: "https://tiktok.com/@karendaou",
                reputationScore: 8.0, nights: 3, shows: 3, noShows: 0, strikes: 0, withYou: 0,
                audienceFemalePct: 0.60, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.80),
                    AudienceCountry(label: "UAE", pct: 0.10),
                    AudienceCountry(label: "Qatar", pct: 0.05),
                ]),
            ApplicantCard(id: "a20", name: "Mira Haddad", gender: "female", photoName: "lina",
                qualityScore: 0.89, instagramFollowers: 47000, tiktokFollowers: 88000,
                instagramURL: "https://instagram.com/mirahaddad", tiktokURL: "https://tiktok.com/@mirahaddad",
                reputationScore: 9.1, nights: 16, shows: 16, noShows: 0, strikes: 0, withYou: 3,
                audienceFemalePct: 0.73, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.65),
                    AudienceCountry(label: "UAE", pct: 0.19),
                    AudienceCountry(label: "KSA", pct: 0.08),
                ]),
            ApplicantCard(id: "a21", name: "Omar Khalil", gender: "male", photoName: "karim",
                qualityScore: 0.80, instagramFollowers: 17000, tiktokFollowers: 25000,
                instagramURL: "https://instagram.com/omarkhalil", tiktokURL: "https://tiktok.com/@omarkhalil",
                reputationScore: 8.4, nights: 8, shows: 7, noShows: 1, strikes: 0, withYou: 1,
                audienceFemalePct: 0.40, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.73),
                    AudienceCountry(label: "UAE", pct: 0.14),
                    AudienceCountry(label: "KSA", pct: 0.06),
                ]),
            ApplicantCard(id: "a22", name: "Ziad Karam", gender: "male", photoName: "rami",
                qualityScore: 0.75, instagramFollowers: 10000, tiktokFollowers: 0,
                instagramURL: "https://instagram.com/ziadkaram",
                reputationScore: 8.1, nights: 4, shows: 4, noShows: 0, strikes: 0, withYou: 0,
                audienceFemalePct: 0.39, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.77),
                    AudienceCountry(label: "Cyprus", pct: 0.11),
                    AudienceCountry(label: "UAE", pct: 0.07),
                ]),
            ApplicantCard(id: "a23", name: "Jad Nassif", gender: "male", photoName: "karim",
                qualityScore: 0.83, instagramFollowers: 23000, tiktokFollowers: 41000,
                instagramURL: "https://instagram.com/jadnassif", tiktokURL: "https://tiktok.com/@jadnassif",
                reputationScore: 8.6, nights: 11, shows: 10, noShows: 1, strikes: 0, withYou: 2,
                audienceFemalePct: 0.44, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.70),
                    AudienceCountry(label: "UAE", pct: 0.15),
                    AudienceCountry(label: "France", pct: 0.08),
                ]),
            ApplicantCard(id: "a24", name: "Marc Abboud", gender: "male", photoName: "rami",
                qualityScore: 0.77, instagramFollowers: 13000, tiktokFollowers: 18000,
                instagramURL: "https://instagram.com/marcabboud", tiktokURL: "https://tiktok.com/@marcabboud",
                reputationScore: 8.3, nights: 6, shows: 6, noShows: 0, strikes: 0, withYou: 1,
                audienceFemalePct: 0.43, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.74),
                    AudienceCountry(label: "Qatar", pct: 0.10),
                    AudienceCountry(label: "UAE", pct: 0.08),
                ]),
            ApplicantCard(id: "a25", name: "Rami Saliba", gender: "male", photoName: "karim",
                qualityScore: 0.85, instagramFollowers: 30000, tiktokFollowers: 52000,
                instagramURL: "https://instagram.com/ramisaliba", tiktokURL: "https://tiktok.com/@ramisaliba",
                reputationScore: 8.8, nights: 14, shows: 13, noShows: 1, strikes: 0, withYou: 2,
                audienceFemalePct: 0.46, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.67),
                    AudienceCountry(label: "UAE", pct: 0.17),
                    AudienceCountry(label: "KSA", pct: 0.09),
                ]),
            ApplicantCard(id: "a26", name: "Elie Tannous", gender: "male", photoName: "rami",
                qualityScore: 0.73, instagramFollowers: 9000, tiktokFollowers: 0,
                instagramURL: "https://instagram.com/elietannous",
                reputationScore: 8.0, nights: 3, shows: 3, noShows: 0, strikes: 0, withYou: 0,
                audienceFemalePct: 0.38, audienceCountries: [
                    AudienceCountry(label: "Lebanon", pct: 0.79),
                    AudienceCountry(label: "Cyprus", pct: 0.09),
                    AudienceCountry(label: "UAE", pct: 0.06),
                ]),
        ]
    }
}
